#!/bin/sh
here="`dirname \"$0\"`"
echo "cd-ing to $here"
cd "$here" || exit 1

rm -rf config.txt
ln -s myMidi2.app/Contents/MacOS/config.txt config.txt
chmod a+rwx config.txt
cat configs/config1 > config.txt
cd myMidi2.app/Contents/MacOS
./myMidi2
cd ../../..
cat configs/config2 > config.txt
cd myMidi2.app/Contents/MacOS
./myMidi2
cd ../../..
cat configs/config3 > config.txt
cd myMidi2.app/Contents/MacOS
./myMidi2
cd ../../..
