#!/bin/sh
here="`dirname \"$0\"`"
echo "cd-ing to $here"
cd "$here" || exit 1

rm -rf config.txt
ln -s myMidi2.app/Contents/MacOS/config.txt config.txt
chmod a+rwx config.txt
cd configs
rm -rf config1
cd ../dist/gui
./gui
cd ../gui2
./gui2
cd ../gui3
./gui3
cd ../../configs
cat config1 > ../config.txt
cd ..
cd myMidi2.app/Contents/MacOS
./myMidi2

